export const LOAD_CATEGORY_LIST = 'LOAD_CATEGORY_LIST';
export const LOAD_CATEGORY_ITEM = 'LOAD_CATEGORY_ITEM';
export const LOAD_CATEGORY_PATH = 'LOAD_CATEGORY_PATH';

export const LOAD_ARTICLE_LIST = 'LOAD_ARTICLE_LIST';
export const LOAD_ARTICLE_ITEM = 'LOAD_ARTICLE_ITEM';
export const LOAD_ARTICLE_PATH = 'LOAD_ARTICLE_PATH';

export const LOAD_RECIPE_LIST = 'LOAD_RECIPE_LIST';
export const LOAD_RECIPE_ITEM = 'LOAD_RECIPE_ITEM';
export const LOAD_RECIPE_PATH = 'LOAD_RECIPE_PATH';
